language: cpp
dist: xenial
compiler: gcc
os:
- linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8
      - libpoco-dev
      

install: cmake .
script: make